spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.datasource.url=jdbc:db2://isp3149:50001/HWNG_DB
spring.datasource.username=db2inst1
spring.datasource.password=db2inst1
spring.datasource.platform=db2
spring.datasource.initialize=false
debug=true
oauth.resource=https://s-accapi.accuroemr.com/rest/v1
oauth.authorize=https://s-accapi.accuroemr.com/
oauth.token=https://s-accapi.accuroemr.com/oauth/token
oauth.tenant=SDMLB
oauth.uuid=1697e08c-867a-4521-a73b-e797e23db96e
oauth.clientId=93640373633-g5obecf9sfs3k6mefjav6ee8fa1fn62n.apps.googleusercontent.com
oauth.clientSecret=IGMABY1NP4RCnuqq2p_OWhUz
oauth.checkTokenUrl=https://www.googleapis.com/oauth2/v3/tokeninfo?access_token={accessToken}
oauth.userInfoUrl: https://www.googleapis.com/plus/v1/people/me
logging.level.org.springframework.security=DEBUG